export const WEEK_DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
export const WEEK_DAYS_FULL = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export const EXERCISE_LIST = [
  'Bench Press',
  'Incline Bench Press',
  'Decline Bench Press',
  'Dumbbell Bench Press',
  'Machine Bench Press',
  'Smith Machine Bench Press',
  'Push Ups',
  'Incline Push Ups',
  'Decline Push Ups',
  'Weighted Push Ups',
  'Chest Fly',
  'Dumbbell Fly',
  'Cable Fly',
  'Machine Fly',
  'Pec Deck Fly',
  'Dips',
  'Pull Ups',
  'Chin Ups',
  'Neutral Grip Pull Ups',
  'Weighted Pull Ups',
  'Lat Pulldown',
  'Close Grip Pulldown',
  'Reverse Grip Pulldown',
  'Barbell Row',
  'Dumbbell Row',
  'One Arm Row',
  'Pendlay Row',
  'T Bar Row',
  'Deadlift',
  'Sumo Deadlift',
  'Romanian Deadlift',
  'Trap Bar Deadlift',
  'Shrugs',
  'Overhead Press',
  'Dumbbell Shoulder Press',
  'Machine Shoulder Press',
  'Arnold Press',
  'Lateral Raise',
  'Front Raise',
  'Rear Delt Fly',
  'Upright Row',
  'Barbell Curl',
  'Dumbbell Curl',
  'Hammer Curl',
  'Concentration Curl',
  'Preacher Curl',
  'Triceps Pushdown',
  'Skull Crushers',
  'Overhead Tricep Extension',
  'Tricep Dips',
  'Close Grip Bench Press',
  'Squat',
  'Front Squat',
  'Goblet Squat',
  'Box Squat',
  'Hack Squat',
  'Bulgarian Split Squat',
  'Lunge',
  'Reverse Lunge',
  'Walking Lunge',
  'Leg Press',
  'Step Up',
  'Calf Raise',
  'Seated Calf Raise',
  'Donkey Calf Raise',
  'Leg Curl',
  'Leg Extension',
  'Hip Thrust',
  'Glute Bridge',
  'Plank',
  'Side Plank',
  'Weighted Plank',
  'Crunches',
  'Decline Crunch',
  'Cable Crunch',
  'Sit Ups',
  'Hanging Leg Raise',
  'Knee Raise',
  'Russian Twist',
  'Bicycle Crunch',
  'Ab Rollout',
  'Mountain Climbers',
  'Flutter Kicks',
  'Side Bends',
  'Running',
  'Sprints',
  'Hill Runs',
  'Treadmill Run',
  'Cycling',
  'Stationary Bike',
  'Spin Bike',
  'Rowing Machine',
  'Jump Rope',
  'Stair Climber',
  'Elliptical',
  'Battle Ropes',
  'Burpees',
  'High Knees',
  'Jump Squats',
  'Box Jumps',
  'Wall Balls',
  'Thrusters',
  'Kettlebell Swing',
  'Farmer’s Carry',
  'Tire Flip',
  'Yoke Carry',
  'Sled Push',
  'Sled Pull',
  'Clean',
  'Jerk',
  'Snatch',
  'Hang Clean',
  'Overhead Squat',
  'Push Press',
  'Power Clean',
  'Muscle Up',
  'Handstand Push Up',
  'Planche',
  'Front Lever',
  'Back Lever',
  'L Sit',
  'Pistol Squat',
  'One Arm Push Up',
  'Pull Over',
  'Good Morning',
  'Chest Supported Row',
  'Incline Row',
  'Face Pull',
  'Cable Row',
  'Incline Curl',
  'Zottman Curl',
  'Spider Curl',
  'Reverse Curl',
  'Incline Fly',
  'Decline Fly',
  'Chest Press Machine',
  'Pec Deck',
  'Landmine Press',
  'Landmine Row',
  'Cable Lateral Raise',
  'Cable Front Raise',
  'Cable Kickback',
  'Cable Curl',
  'Incline Skull Crusher',
  'JM Press',
  'Sissy Squat',
  'Jefferson Squat',
  'Hack Squat Machine',
  'Hip Abduction',
  'Hip Adduction',
  'Nordic Curl',
  'Glute Kickback',
  'Cable Pull Through',
  'Sumo Squat',
  'Cossack Squat',
  'Box Step Over',
  'Reverse Hyperextension',
  'Weighted Carry',
  'Turkish Get Up',
  'Bear Crawl',
  'Inchworm',
  'Burpee Pull Up',
  'Burpee Box Jump',
  'Man Maker',
  'Devil Press',
  'Clean and Jerk',
  'Snatch Grip Deadlift',
  'Power Snatch',
  'Bar Muscle Up',
  'Ring Dip',
  'Ring Row',
  'Toes to Bar',
  'Kipping Pull Up',
  'Double Unders',
  'Single Unders',
  'Assault Bike',
  'Air Bike',
  'Ski Erg',
  'Farmer Walk',
  'Sandbag Carry',
  'Atlas Stone Lift',
  'Log Press',
  'Axle Clean and Press',
  'Rope Climb',
  'Pegboard Climb',
  'Handstand Walk',
  'Prowler Push',
  'Weighted Step Up',
  'Weighted Vest Run',
  'Sled Drag',
  'Suitcase Carry',
  'Overhead Carry',
  'Duck Walk',
  'Seal Row',
  'Machine Row',
  'Machine Chest Press',
  'Hack Deadlift',
  'Snatch Grip Row',
  'Pendulum Squat',
  'Reverse Hack Squat',
  'Machine Shrugs',
  'Machine Lateral Raise',
  'Machine Rear Delt Fly',
  'Machine Shoulder Press',
  'Machine Preacher Curl',
  'Machine Leg Press',
  'Machine Leg Extension',
  'Machine Hamstring Curl',
  'Machine Calf Raise',
  'Diamond Push Up',
  'Clap Push Up',
  'Archer Push Up',
  'Pseudo Planche Push Up',
  'One Arm Pull Up',
  'Chest Dip',
  'Tricep Dip',
  'Ring Push Up',
  'Weighted Dip',
  'Weighted Chin Up',
  'Negative Pull Up',
  'Assisted Pull Up',
  'Box Squat Jump',
  'Depth Jump',
  'Broad Jump',
  'Sprint Start Jump',
  'Lunge Jump',
  'Split Squat Jump',
  'Step Up Jump',
  'Kettlebell Deadlift',
  'Kettlebell Clean',
  'Kettlebell Press',
  'Kettlebell Snatch',
  'Kettlebell Goblet Squat',
  'Kettlebell Front Squat',
  'Kettlebell Swing Clean',
  'Kettlebell Turkish Get Up',
  'Kettlebell Windmill',
  'Dumbbell Deadlift',
  'Dumbbell Snatch',
  'Dumbbell Clean',
  'Dumbbell Thruster',
  'Dumbbell Swing',
  'Dumbbell Lunge',
  'Dumbbell Step Up',
  'Dumbbell Overhead Squat',
  'Dumbbell Press Out',
  'Resistance Band Curl',
  'Resistance Band Row',
  'Resistance Band Pull Apart',
  'Resistance Band Squat',
  'Resistance Band Deadlift',
  'Resistance Band Press',
  'Resistance Band Lateral Walk',
  'Resistance Band Kickback',
  'Foam Roll Quads',
  'Foam Roll Hamstrings',
  'Foam Roll Calves',
  'Foam Roll Glutes',
  'Foam Roll Back',
  'Hamstring Stretch',
  'Quad Stretch',
  'Hip Flexor Stretch',
  'Shoulder Stretch',
  'Chest Stretch',
  'Tricep Stretch',
  'Cat Cow Stretch',
  'Downward Dog',
  'Warrior Pose',
  'Child’s Pose',
  'Bridge Pose',
  'Sun Salutation',
  'Cobra Pose',
  'Seated Twist',
];

// Metabolic Equivalent of Task values for calorie calculation
// Sourced from various fitness studies, providing a general estimate.
export const MET_VALUES: Record<string, number> = {
  'Bench Press': 6.0,
  'Squat': 5.5,
  'Deadlift': 7.0,
  'Overhead Press': 4.5,
  'Barbell Row': 6.0,
  'Pull Up': 8.0,
  'Chin Up': 8.0,
  'Dip': 7.0,
  'Push Up': 8.0,
  'Lat Pulldown': 4.0,
  'Dumbbell Press': 5.0,
  'Dumbbell Flyes': 3.5,
  'Incline Bench Press': 5.0,
  'Leg Press': 5.0,
  'Leg Curl': 3.5,
  'Leg Extension': 3.0,
  'Calf Raise': 3.0,
  'Bicep Curl': 3.0,
  'Triceps Extension': 2.5,
  'Lateral Raise': 3.0,
  'Shoulder Press': 4.5,
  'Face Pull': 2.5,
  'Plank': 3.0,
  'Crunches': 3.8,
  'Russian Twist': 3.5,
  'Lunges': 4.0,
  'Running': 9.8,
  'Cycling': 7.5,
  'Swimming': 8.0,
  'Rowing Machine': 7.0,
  'Kettlebell Swing': 9.0,
  'Battle Ropes': 8.5,
  'Box Jump': 8.0,
  'Burpees': 9.0,
  'Sit-ups': 4.5,
  'Hanging Leg Raise': 5.0,
  'T-Bar Row': 6.0,
  'Seated Cable Row': 4.0,
};

// More general MET values for the calorie burn calculator
export const GENERAL_ACTIVITY_MET_VALUES: Record<string, number> = {
  'Weight Lifting (general)': 5.0,
  'Running (moderate, ~10 min/mile)': 9.8,
  'Cycling (moderate, ~12-14 mph)': 7.5,
  'Yoga': 3.0,
  'Swimming (freestyle, moderate)': 8.0,
  'Walking (moderate, ~3 mph)': 3.5,
  'HIIT (High-Intensity Interval Training)': 11.0,
  'Rowing (moderate)': 7.0,
};
